root = "."
tmp_dir = "tmp"

[build]
  stop_on_error = true
  delay = 100
  log = "air-build-errors.log"
  rerun = false
  exclude_dir = ["load-test"]

[log]
  time = true

[misc]
  clean_on_exit = false
