version: '3.9'

services:
  api:
    image: go-crebito
    build:
      dockerfile: Dockerfile
      target: dev
    environment:
      SERVER_ADDRESS: 4000
      DB_HOST: db
      DB_USER: rinheiro
      DB_PASSWORD: rinha123
      DB_NAME: rinha-go-crebito
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: rinheiro
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinha-go-crebito
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seed.sql:/seed.sql
      - ./tmp/psql_history:/root/.psql_history
      - ./tmp/bash_history:/root/.bash_history
    ports:
      - 5432:5432
