version: '3.9'

services:
  api1: &api
    image: lucassperez/go-crebito:latest
    build:
      dockerfile: Dockerfile
      target: prod
    hostname: api1
    environment:
      # The db service's name
      PG_HOST: db
    volumes:
      - .:/app
    ports:
      # host:container
      - 4000:4000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: '60MB'

  api2:
    <<: *api
    hostname: api2
    ports:
      - 4001:4000

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha-go-crebito
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: '400MB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '30MB'
