version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
      target: dev
    image: go-crebito-local
    environment:
      # The db service's name
      PG_HOST: db
      SERVER_ADDRESS: 4000
    volumes:
      - .:/app
    ports:
      # host:container
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha-go-crebito
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seed.sql:/seed.sql
      - ./tmp/psql_history:/root/.psql_history
      - ./tmp/bash_history:/root/.bash_history
    ports:
      - 5432:5432
